#!/usr/bin/env python3
"""Self-checking fuzzer for the char-indexed string ops and the form-start scanner.

**Why an oracle rather than an engine differential.** The two caches these ops now sit on
— the string slot's sparse char→byte index (ADR-213) and the form-start safepoint table
(ADR-214) — live on the *heap*, not in an engine, so all four engine configs share them and
would agree on a wrong answer. A divergence run cannot see that. Each generated program
therefore checks every result against a reference computed a different way (a code-point
vector, or a property that must hold), and prints `BAD …` on a mismatch, which
`scripts/fuzz/run.sh` greps for. The engine sweep still adds value on top: the same
programs run under the tree-walker, the VM, the JIT and GC-stress + verify.

The corpus deliberately mixes 1-, 2-, 3- and 4-byte characters at random positions, and
half the strings are long enough (> 256 chars) to be *indexed* rather than walked — the two
code paths differ, and only one of them is exercised by short fixtures.

    scripts/fuzz/run.sh strings 200
"""
import random
import sys
from pathlib import Path

# 1-, 2-, 3- and 4-byte characters, plus the ones the sexp lexer cares about.
CHARS = ["a", "z", "0", " ", "\\n", "é", "ß", "€", "漢", "🙂", "(", ")", "[", "]", ";", "\\\""]
# Weighted so brackets/quotes/semicolons appear often enough to matter to the scanner,
# without drowning out the multi-byte characters the index exists for.
WEIGHTS = [14, 6, 6, 10, 8, 8, 4, 4, 6, 6, 6, 6, 2, 2, 5, 3]


def text(rng, n):
    return "".join(rng.choices(CHARS, weights=WEIGHTS, k=n))


def program(seed):
    rng = random.Random(seed)
    # Half short (walked), half past the 256-char index threshold (indexed).
    n = rng.choice([rng.randint(0, 40), rng.randint(260, 900)])
    body = text(rng, n)
    needle = "".join(rng.choices(CHARS, weights=WEIGHTS, k=rng.randint(1, 3)))
    src_lines = rng.randint(2, 12)
    return f'''
;; GENERATED by scripts/fuzz/generators/strings.py — seed {seed}
;; Every op is checked against a reference computed from the code-point vector, so a wrong
;; char->byte conversion is caught here rather than becoming a silently wrong substring.
(def s "{body}")
(def needle "{needle}")
(def cps (into [] (string->list s)))
(def n (string/length s))

(defn bad (what a b) (println "BAD" what "got" (pr-str a) "want" (pr-str b)))
(defn chk (what a b) (if (= a b) 0 (do (bad what a b) 1)))

;; substring / char-at against slices of the code-point vector
(defn ref-sub (i j) (apply str (subvec cps i j)))
(defn chk-slices (i acc)
  (if (>= i n)
    acc
    (let (j (min n (+ i 1 (rem (* i 7) 5))))
      (chk-slices (+ i 1)
        (+ acc (chk "substring" (substring s i j) (ref-sub i j))
           (chk "char-at" (char-at s i) (nth cps i)))))))

;; string/length agrees with the code-point count, and the whole string round-trips
(def errs0 (+ (chk "string/length" n (count cps))
              (chk "roundtrip" s (apply str cps))
              (chk "substring-all" (substring s 0 n) s)))

;; index-of with a rising `from` must find occurrences in order, each one really there
(defn chk-scan (from acc)
  (let (j (index-of s needle from))
    (if (< j 0)
      acc
      (chk-scan (+ j 1)
        (+ acc (chk "index-of-at" (substring s j (min n (+ j (string/length needle))))
                 (if (<= (+ j (string/length needle)) n) needle
                   (substring s j n)))
           (if (>= j from) 0 (do (bad "index-of-order" j from) 1)))))))

;; last-index-of: the reported position holds the needle, and nothing after it does
(def errs2
  (let (last (last-index-of s needle))
    (if (< last 0)
      (chk "no-needle" (index-of s needle 0) -1)
      (+ (chk "last-index-of-at" (substring s last (min n (+ last (string/length needle))))
           (if (<= (+ last (string/length needle)) n) needle (substring s last n)))
         (chk "nothing-after-last" (index-of s needle (+ last 1)) -1)))))

;; string/span: `e` is just PAST the maximal run of set members from `i`, so every char in
;; [i, e) is in the set and the char AT `e` (if any) is not.
(defn all-in-set (set i e)
  (if (>= i e) true (if (includes? set (char-at s i)) (all-in-set set (+ i 1) e) false)))
(def errs3
  (let (set " \\n" i (min (max 0 (quot n 2)) (max 0 (- n 1)))
        e (string/span s i set))
    (if (= n 0) 0
      (+ (if (and (>= e i) (<= e n)) 0 (do (bad "span-range" e n) 1))
         (if (all-in-set set i e) 0 (do (bad "span-run-not-all-in-set" i e) 1))
         (if (or (= e n) (not (includes? set (char-at s e)))) 0
           (do (bad "span-stopped-early" (char-at s e) set) 1))))))

;; the form-start scanner (ADR-214's safepoint table) as a property: the answer is at or
;; before `pos`, at a line start, and is a bracket — or 0 when there is no form start.
(def src (apply str (repeat {src_lines} "(defn f (a) (str \\"x\\" a))\\n")))
(defn chk-form (pos acc)
  (if (>= pos (string/length src))
    acc
    (let (b (scan-form-start src pos))
      (chk-form (+ pos 3)
        (+ acc
           (if (<= b pos) 0 (do (bad "form-start-after-pos" b pos) 1))
           (if (or (= b 0) (= (char-at src (- b 1)) "\\n")) 0
             (do (bad "form-start-not-bol" b (char-at src (- b 1))) 1))
           (if (includes? "([{{" (char-at src b)) 0
             (do (bad "form-start-not-bracket" (char-at src b) b) 1)))))))

(println "checked"
  (+ errs0 errs2 errs3 (chk-slices 0 0) (chk-scan 0 0) (chk-form 0 0)))
'''


def main():
    count = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    base = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    out = Path(sys.argv[3] if len(sys.argv) > 3 else ".")
    out.mkdir(parents=True, exist_ok=True)
    for k in range(count):
        seed = base + k
        (out / f"str_{seed}.blsp").write_text(program(seed))
    print(f"wrote {count} programs to {out}")


if __name__ == "__main__":
    main()
